#!/usr/bin/env python3

# Run veusz here without installation, to make development easier
# automatically sets the resource directory to be this directory

#    Copyright (C) 2013 Jeremy S. Sanders
#    Email: Jeremy Sanders <jeremy@jeremysanders.net>
#
#    This file is part of Veusz.
#
#    Veusz is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    Veusz is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Veusz. If not, see <https://www.gnu.org/licenses/>.
#
##############################################################################

import os.path
import sys

try:
    import veusz
except ImportError:
    thisdir = os.path.abspath( os.path.dirname(__file__) )
    sys.path = [thisdir] + sys.path
    import veusz

import veusz.veusz_main
veusz.veusz_main.run()
