#!/usr/bin/env python

# Run main veusz python script
# This is licenced under the GNU General Public Licence, v2 or greater
# see the file COPYING for details

# horrible magic go get path correct
# we need to get the veusz module into the python path
import imp
import sys
import os.path

# this finds the path of the veusz module
path = imp.find_module('veusz')[1]

# add to the python path
sys.path.insert(0, os.path.abspath(path))

# import the veusz.py in the veusz module
import veusz
veusz.run()
