#!/usr/bin/env python

# Run veusz listening script
# This is licenced under the GNU General Public Licence, v2 or greater
# see the file COPYING for details

# $Id:$

import veusz.veusz_listen
veusz.veusz_listen.run()
