#!/usr/bin/env python

# Run main veusz python script
# This is licenced under the GNU General Public Licence, v2 or greater
# see the file COPYING for details

# $Id:$

import veusz.veusz_main
veusz.veusz_main.run()
