# Veusz build using distribution packages on Ubuntu

name: Ubuntu build using distribution packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install \
          libqt5core5a libqt5dbus5 libqt5gui5 libqt5svg5 libqt5widgets5 libqt5xml5 \
          python3-all python3-astropy python3-h5py python3-pyqt5 python3-pyqt5.qtsvg \
          python3-setuptools python3-numpy python3-qtpy qt5-qmake qt5-default
    - name: Build extensions
      run: |
        python3 setup.py build_ext --inplace
    - name: Run tests
      run: |
        QT_QPA_PLATFORM=minimal VEUSZ_INPLACE_TEST=1 python3 tests/runselftest.py
