name: mypy

on:
  push:
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Install mypy
        run: |
          pip install -r requirements.txt
          pip install mypy
      - name: Run mypy
        run: |
          mypy .
